apiVersion: v1
kind: Service
metadata:
  name: releasebus-githubapi
  namespace: appstacking
spec:
  type: ClusterIP
  ports:
    - name: rpc
      port: 80
      targetPort: 12001
      protocol: TCP
  selector:
    app: releasebus-githubapi
    ns: appstacking